
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || "https://dbgklihhoflrvqvkfdzi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY || "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRiZ2tsaWhob2ZscnZxdmtmZHppIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYxNTU5MDksImV4cCI6MjA2MTczMTkwOX0.t_ZUUYBYzPYPn7F-bjLvRCU9QhlWq6EdX99VM98mFPY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
